version: '3.7'

services:
  redis:
    image: redis:6.0.6
    ports:
      - "6379:6379"
  
  redisui:
    image: marian/rebrow
    ports:
      - "5001:5001"
    links:
      - redis:redis
    depends_on:
      - "redis"
      


 



